### ISSUE TITLE
Version 0.1.0 checklist

### ISSUE THREAD

**Issue by Alexander-Prime** [AlwaysBeCrafting/rss-in-discord#3]
- [x] User can add a feed
- [x] Bot creates new chat posts when feeds update
  - [x] "Links only" formatting only
- [x] User can remove feeds (any user for now, no permissions)
- [x] Bot creates and listens to a "reaction bar" for common actions

- [x] Docker is used to start/stop development server
